name: ptolemay_test
description: Test app for Ptolemay interview
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  equatable: ^2.0.5
  provider: ^6.0.5
  weather: ^3.1.1
  geolocator: ^10.0.1
  talker_flutter: ^3.3.1
  talker_bloc_logger: ^2.2.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  generate: true
